# Generated by Django 4.0 on 2022-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='photo',
            field=models.ImageField(default='static/base/images/room-1.jpg', upload_to='static/base/images/'),
        ),
    ]
