# Generated by Django 4.0 on 2021-12-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=13, verbose_name='FIO')),
                ('phone_no', models.CharField(max_length=13, verbose_name='Phone No')),
                ('post', models.CharField(choices=[('горничная', 'Горничная'), ('администратор', 'Администратор'), ('менеджер', 'Менеджер'), ('директор', 'Директор')], max_length=32, verbose_name='Post')),
                ('passport_no', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff')),
            ],
        ),
    ]
