# Generated by Django 4.0 on 2021-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='FIO'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='passport_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.CharField(choices=[('горничная', 'Горничная'), ('администратор', 'Администратор'), ('менеджер', 'Менеджер'), ('директор', 'Директор')], max_length=20, verbose_name='Post'),
        ),
    ]
