# Generated by Django 4.0 on 2021-12-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_fio_alter_staff_passport_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'post': 'Горничная'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_no',
            field=models.CharField(max_length=12, verbose_name='Phone No'),
        ),
    ]
