# Generated by Django 4.0 on 2021-12-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_schedules_staff_alter_staff_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'post': 'горничная'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff'),
        ),
    ]
