# Generated by Django 4.0 on 2021-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_schedules_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
